#!/bin/bash
#SBATCH -J ExpRunner
#SBATCH -p bme_gpu4
#SBATCH --time=4-00:00:00
#SBATCH --mem=100G
#SBATCH -N 1
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:1

#SBATCH -o logs/%j_stdout.log
#SBATCH -e logs/%j_stderr.log

echo ${SLURM_JOB_NODELIST}
echo start on $(date)

# module load apps/fsl/6.0
# module load apps/ants
# . ${FSLDIR}/etc/fslconf/fsl.sh
source /public_bme/data/gujch/programs/anaconda3/bin/activate /public_bme/data/gujch/programs/anaconda3/envs/tnn

$1
